/**
 * gen-default-content.mts — build content/site-content.json from the app's
 * source-of-truth defaults in src/data/content.ts.
 *
 * Run once to seed the repo content file (then keep it up to date with
 * `npm run content:export` after editing via the admin panel / MCP):
 *   npx tsx scripts/gen-default-content.mts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as d from '../src/data/content';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../content/site-content.json');

// Mirror the CMS ContentState shape, but skip runtime-only logs (version
// history / audit logs) which are regenerated by the app, not authored content.
const content: Record<string, unknown> = {
  PERSONAL_INFO: d.PERSONAL_INFO,
  SERVICES: d.SERVICES,
  CASE_STUDIES: d.CASE_STUDIES,
  STATS: (d as any).STATS,
  TESTIMONIALS: (d as any).TESTIMONIALS,
  BLOG_POSTS: d.BLOG_POSTS,
  PRODUCTS: d.PRODUCTS,
  PROJECTS_PAGE_DATA: d.PROJECTS_PAGE_DATA,
  PRODUCTS_PAGE_DATA: d.PRODUCTS_PAGE_DATA,
  CHAT_CONFIG: d.CHAT_CONFIG,
  AI_TOOLS_CONFIG: d.AI_TOOLS_CONFIG,
  BLOG_PAGE_DATA: (d as any).BLOG_PAGE_DATA,
  ONGOING_PROJECTS: (d as any).ONGOING_PROJECTS,
  BUSINESS_ANALYSIS_DATA: (d as any).BUSINESS_ANALYSIS_DATA,
  SKILLS_TOOLS: (d as any).SKILLS_TOOLS,
  ALL_SKILLS_LIST: (d as any).ALL_SKILLS_LIST,
  TIMELINE: (d as any).TIMELINE,
  OTHER_COLLABORATIONS: (d as any).OTHER_COLLABORATIONS,
  SELECT_PROJECTS: (d as any).SELECT_PROJECTS,
  EDUCATION_AND_COURSES: (d as any).EDUCATION_AND_COURSES,
  HOW_I_WORK_STEPS: d.HOW_I_WORK_STEPS,
  HOMEPAGE_HOW_I_WORK_STEPS: d.HOMEPAGE_HOW_I_WORK_STEPS,
  WHY_OMID_POINTS: (d as any).WHY_OMID_POINTS,
  CUSTOM_PAGES: [],
  PAGE_SEO: {},
};

// Drop undefined keys (exports that may not exist).
for (const k of Object.keys(content)) if (content[k] === undefined) delete content[k];

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(content, null, 2) + '\n', 'utf8');
console.log(`[gen-default-content] wrote ${OUT} (${Object.keys(content).length} sections)`);
